info:
  contact: {}
paths:
  /api/heartbeat:
    get:
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Heartbeat metric
      tags:
      - Metrics
  /api/v1/group/{groupName}/spieces:
    get:
      parameters:
      - description: Name of the group
        in: path
        name: groupName
        required: true
        type: string
      - description: from
        in: query
        name: from
        type: integer
      - description: till
        in: query
        name: till
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Spieces in group
      tags:
      - Groups
  /api/v1/group/{groupName}/spieces/top/{N}:
    get:
      parameters:
      - description: Name of the group
        in: path
        name: groupName
        required: true
        type: string
      - description: Top N
        in: path
        name: "N"
        required: true
        type: string
      - description: from
        in: query
        name: from
        type: integer
      - description: till
        in: query
        name: till
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Top N spieces in group
      tags:
      - Groups
  /api/v1/group/{groupName}/temperature/average:
    get:
      parameters:
      - description: Name of the group
        in: path
        name: groupName
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Average temperature in group
      tags:
      - Groups
  /api/v1/group/{groupName}/transparency/average:
    get:
      parameters:
      - description: Name of the group
        in: path
        name: groupName
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Average transparency in group
      tags:
      - Groups
  /api/v1/region/temperature/max:
    get:
      parameters:
      - description: Minimum value for x coordinate
        in: query
        name: xMin
        required: true
        type: string
      - description: Minimum value for y coordinate
        in: query
        name: yMin
        required: true
        type: string
      - description: Minimum value for z coordinate
        in: query
        name: zMin
        required: true
        type: string
      - description: Maximum value for x coordinate
        in: query
        name: xMax
        required: true
        type: string
      - description: Maximum value for y coordinate
        in: query
        name: yMax
        required: true
        type: string
      - description: Maximum value for z coordinate
        in: query
        name: zMax
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Max Temperature
      tags:
      - Sensors
  /api/v1/region/temperature/min:
    get:
      parameters:
      - description: Minimum value for x coordinate
        in: query
        name: xMin
        required: true
        type: string
      - description: Minimum value for y coordinate
        in: query
        name: yMin
        required: true
        type: string
      - description: Minimum value for z coordinate
        in: query
        name: zMin
        required: true
        type: string
      - description: Maximum value for x coordinate
        in: query
        name: xMax
        required: true
        type: string
      - description: Maximum value for y coordinate
        in: query
        name: yMax
        required: true
        type: string
      - description: Maximum value for z coordinate
        in: query
        name: zMax
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Min Temperature
      tags:
      - Sensors
  /api/v1/sensor/{codeName}/temperature/average:
    get:
      parameters:
      - description: Name of the group
        in: path
        name: codeName
        required: true
        type: string
      - description: from
        in: query
        name: from
        type: integer
      - description: till
        in: query
        name: till
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Average Temperature
      tags:
      - Sensors
swagger: "2.0"
